In [1]:
import tensorflow as tf
import numpy as np
from auxiliary import auxiliary_net
import pandas as pd

def shuffle_data(x_data, y_data):
    data = np.concatenate((x_data, y_data), axis = 1)
    np.random.shuffle(data)
    x_data_shfl = data[:, :x_data.shape[1]]
    y_data_shfl = data[:, x_data.shape[1]:]
    return x_data_shfl, y_data_shfl



def next_batch(x_data, y_data, batch_size, startpoint):
    # assume the data has been shuffled
    
    endpoint = startpoint + batch_size
    if endpoint > x_data.shape[0]:
        x_batch = x_data[startpoint: , :]
        y_batch = y_data[startpoint: , :]
    else:
        x_batch = x_data[startpoint:endpoint, :]
        y_batch = y_data[startpoint:endpoint, :]
    
    return x_batch, y_batch, endpoint

In [2]:
# importing data (and preprocessing it e.g. noramlization)

data = pd.read_excel("auxiliary_data/dummy_test.xlsx")
data.head()
data_array = data.values
print(data_array)

# training - test data split: 75% - 25%
np.random.shuffle(data_array)
no_samples = data_array.shape[0]
train = data_array[ :int(round(0.75*no_samples,0)),:]
test = data_array[int(round(0.75*no_samples,0)): ,:]

x_train = train[:, :-1]
y_train = train[:,-1]
y_train = np.reshape(y_train, [y_train.shape[0], 1])

x_test = test[:, :-1]
y_test = test[:, -1]
y_test = np.reshape(y_test, [y_test.shape[0], 1])

[[4 0 0 3 1 0]
 [5 5 0 5 0 0]
 [5 6 1 3 2 0]
 ..., 
 [4 4 1 2 0 1]
 [4 5 1 4 0 0]
 [4 6 1 3 2 0]]


In [3]:
# data-related settings
input_size = x_train.shape[1]    #assuming data_x is of shape [N, input_size]
output_size = y_train.shape[1]   #assuming data_y is of shape [N, output_size]
data_type = "real-valued"

# training-related settings 
no_epochs = 300
batch_size = 50

if data_type == "ordinal":
    no_levels = 9

In [4]:
with tf.Session() as sess:
    
    # instantiation
    if data_type == "ordinal":
        dummy_net = auxiliary_net(sess, input_size, output_size, data_type, no_levels = no_levels)
    else:
        dummy_net = auxiliary_net(sess, input_size, output_size, data_type)
    
    # initializing variables in the computational graph
    tf.global_variables_initializer().run()
    
    for epoch in range(no_epochs):
        # shuffle data
        x_train, y_train = shuffle_data(x_train, y_train)
        
        endpoint = 0
        while endpoint <= x_train.shape[0]:
            # extract next training batch
            startpoint = endpoint
            x_batch, y_batch, endpoint = next_batch(x_train, y_train, batch_size, startpoint)
            
            # training
            loss, _ = dummy_net.update(x_batch, y_batch)
            print("epoch %d: loss = %.5f" % (epoch, loss))
    
    # evaluation (prediction based on test data)

    pred_values, eval_metric = dummy_net.predict(x_test, y_test)
    print("eval_metric: %.5f" % eval_metric)

epoch 0: loss = 10.89825
epoch 0: loss = 10.62897
epoch 0: loss = 9.64488
epoch 0: loss = 9.21087
epoch 0: loss = 8.91436
epoch 0: loss = 12.62439
epoch 0: loss = 8.62561
epoch 0: loss = 11.26627
epoch 0: loss = 8.47623
epoch 0: loss = 7.38061
epoch 0: loss = 6.24425
epoch 0: loss = 7.64035
epoch 0: loss = 6.56282
epoch 0: loss = 5.82252
epoch 0: loss = 5.77844
epoch 0: loss = 5.01186
epoch 0: loss = 6.00818
epoch 0: loss = 5.88867
epoch 0: loss = 5.09947
epoch 0: loss = 4.56040
epoch 0: loss = 4.56920
epoch 0: loss = 3.86116
epoch 0: loss = 4.62190
epoch 0: loss = 3.99989
epoch 0: loss = 3.78394
epoch 1: loss = 3.25810
epoch 1: loss = 3.56554
epoch 1: loss = 2.58853
epoch 1: loss = 2.87101
epoch 1: loss = 2.89575
epoch 1: loss = 2.65202
epoch 1: loss = 3.33604
epoch 1: loss = 2.22891
epoch 1: loss = 2.50040
epoch 1: loss = 2.36911
epoch 1: loss = 2.24751
epoch 1: loss = 2.02309
epoch 1: loss = 1.89603
epoch 1: loss = 2.11225
epoch 1: loss = 3.07042
epoch 1: loss = 1.38196
epoch 1: los

epoch 17: loss = 0.26794
epoch 17: loss = 0.24268
epoch 17: loss = 0.26729
epoch 17: loss = 0.33919
epoch 17: loss = 0.27800
epoch 17: loss = 0.67024
epoch 17: loss = 0.47186
epoch 17: loss = 0.37185
epoch 17: loss = 0.41160
epoch 17: loss = 0.57427
epoch 17: loss = 0.96568
epoch 17: loss = 0.37552
epoch 17: loss = 0.24433
epoch 17: loss = 0.25160
epoch 17: loss = 0.20087
epoch 17: loss = 0.38789
epoch 17: loss = 0.29305
epoch 17: loss = 0.30901
epoch 17: loss = 0.32705
epoch 17: loss = 0.54258
epoch 17: loss = 0.28543
epoch 17: loss = 0.56869
epoch 17: loss = 0.31382
epoch 17: loss = 0.31904
epoch 17: loss = 0.23691
epoch 18: loss = 0.74766
epoch 18: loss = 0.31743
epoch 18: loss = 0.42551
epoch 18: loss = 0.40662
epoch 18: loss = 0.27954
epoch 18: loss = 0.26416
epoch 18: loss = 0.49198
epoch 18: loss = 0.32192
epoch 18: loss = 0.28959
epoch 18: loss = 0.36831
epoch 18: loss = 0.38854
epoch 18: loss = 0.48424
epoch 18: loss = 0.26459
epoch 18: loss = 0.35382
epoch 18: loss = 0.24394


epoch 34: loss = 0.26388
epoch 34: loss = 0.20227
epoch 34: loss = 0.24653
epoch 34: loss = 0.17998
epoch 34: loss = 0.16841
epoch 34: loss = 0.07435
epoch 34: loss = 0.16151
epoch 34: loss = 0.08907
epoch 34: loss = 0.08386
epoch 34: loss = 0.16789
epoch 34: loss = 0.22783
epoch 34: loss = 0.15078
epoch 34: loss = 0.21811
epoch 34: loss = 0.07210
epoch 34: loss = 0.08603
epoch 34: loss = 0.18859
epoch 34: loss = 0.11445
epoch 34: loss = 0.16174
epoch 35: loss = 0.14134
epoch 35: loss = 0.06717
epoch 35: loss = 0.15802
epoch 35: loss = 0.11953
epoch 35: loss = 0.09200
epoch 35: loss = 0.06774
epoch 35: loss = 0.14599
epoch 35: loss = 0.72429
epoch 35: loss = 0.10749
epoch 35: loss = 0.10250
epoch 35: loss = 0.05937
epoch 35: loss = 0.14055
epoch 35: loss = 0.12619
epoch 35: loss = 0.08111
epoch 35: loss = 0.30890
epoch 35: loss = 0.15422
epoch 35: loss = 0.36124
epoch 35: loss = 0.25459
epoch 35: loss = 0.17819
epoch 35: loss = 0.11376
epoch 35: loss = 0.22898
epoch 35: loss = 0.11355


epoch 47: loss = 0.09584
epoch 47: loss = 0.09028
epoch 47: loss = 0.13356
epoch 47: loss = 0.10888
epoch 47: loss = 0.07681
epoch 47: loss = 0.08436
epoch 47: loss = 0.19472
epoch 47: loss = 0.11840
epoch 47: loss = 0.34605
epoch 47: loss = 0.62217
epoch 47: loss = 0.11309
epoch 47: loss = 0.06655
epoch 47: loss = 0.10836
epoch 48: loss = 0.15109
epoch 48: loss = 0.07256
epoch 48: loss = 0.06263
epoch 48: loss = 0.07975
epoch 48: loss = 0.10536
epoch 48: loss = 0.11154
epoch 48: loss = 0.14394
epoch 48: loss = 0.16037
epoch 48: loss = 0.06180
epoch 48: loss = 0.14800
epoch 48: loss = 0.60664
epoch 48: loss = 0.16110
epoch 48: loss = 0.11137
epoch 48: loss = 0.14020
epoch 48: loss = 0.14410
epoch 48: loss = 0.04200
epoch 48: loss = 0.14087
epoch 48: loss = 0.11070
epoch 48: loss = 0.10566
epoch 48: loss = 0.14413
epoch 48: loss = 0.30183
epoch 48: loss = 0.10665
epoch 48: loss = 0.10222
epoch 48: loss = 0.06298
epoch 48: loss = 0.20869
epoch 49: loss = 0.23689
epoch 49: loss = 0.07681


epoch 61: loss = 0.04603
epoch 61: loss = 0.04877
epoch 61: loss = 0.14614
epoch 61: loss = 0.06641
epoch 61: loss = 0.12213
epoch 61: loss = 0.05359
epoch 61: loss = 0.07492
epoch 61: loss = 0.11654
epoch 62: loss = 0.06037
epoch 62: loss = 0.05563
epoch 62: loss = 0.22854
epoch 62: loss = 0.13281
epoch 62: loss = 0.05892
epoch 62: loss = 0.10906
epoch 62: loss = 0.08988
epoch 62: loss = 0.55176
epoch 62: loss = 0.07300
epoch 62: loss = 0.11277
epoch 62: loss = 0.09486
epoch 62: loss = 0.10104
epoch 62: loss = 0.07567
epoch 62: loss = 0.25290
epoch 62: loss = 0.04900
epoch 62: loss = 0.12011
epoch 62: loss = 0.10008
epoch 62: loss = 0.07607
epoch 62: loss = 0.06388
epoch 62: loss = 0.09383
epoch 62: loss = 0.12143
epoch 62: loss = 0.08403
epoch 62: loss = 0.11784
epoch 62: loss = 0.17532
epoch 62: loss = 0.06455
epoch 63: loss = 0.16787
epoch 63: loss = 0.09320
epoch 63: loss = 0.55417
epoch 63: loss = 0.07166
epoch 63: loss = 0.06007
epoch 63: loss = 0.08020
epoch 63: loss = 0.04796


epoch 78: loss = 0.14398
epoch 78: loss = 0.08223
epoch 78: loss = 0.12080
epoch 78: loss = 0.05653
epoch 78: loss = 0.10875
epoch 78: loss = 0.06825
epoch 78: loss = 0.12871
epoch 78: loss = 0.04956
epoch 78: loss = 0.08686
epoch 78: loss = 0.06214
epoch 78: loss = 0.05991
epoch 78: loss = 0.08005
epoch 78: loss = 0.05687
epoch 78: loss = 0.10177
epoch 78: loss = 0.04895
epoch 78: loss = 0.07008
epoch 78: loss = 0.13430
epoch 78: loss = 0.08262
epoch 78: loss = 0.11791
epoch 78: loss = 0.56342
epoch 78: loss = 0.06042
epoch 78: loss = 0.08987
epoch 78: loss = 0.04989
epoch 78: loss = 0.05615
epoch 78: loss = 0.04028
epoch 79: loss = 0.09260
epoch 79: loss = 0.08116
epoch 79: loss = 0.04428
epoch 79: loss = 0.07364
epoch 79: loss = 0.43939
epoch 79: loss = 0.09548
epoch 79: loss = 0.09875
epoch 79: loss = 0.06566
epoch 79: loss = 0.08970
epoch 79: loss = 0.05709
epoch 79: loss = 0.03692
epoch 79: loss = 0.06020
epoch 79: loss = 0.16500
epoch 79: loss = 0.18167
epoch 79: loss = 0.07254


epoch 91: loss = 0.07207
epoch 91: loss = 0.05489
epoch 91: loss = 0.10674
epoch 91: loss = 0.05177
epoch 91: loss = 0.10801
epoch 91: loss = 0.02506
epoch 91: loss = 0.02836
epoch 91: loss = 0.09394
epoch 91: loss = 0.06107
epoch 91: loss = 0.18035
epoch 91: loss = 0.04506
epoch 91: loss = 0.05247
epoch 91: loss = 0.06279
epoch 91: loss = 0.07915
epoch 91: loss = 0.36850
epoch 91: loss = 0.04384
epoch 91: loss = 0.09585
epoch 91: loss = 0.04535
epoch 91: loss = 0.10094
epoch 91: loss = 0.14523
epoch 91: loss = 0.04083
epoch 92: loss = 0.06769
epoch 92: loss = 0.08361
epoch 92: loss = 0.05185
epoch 92: loss = 0.11258
epoch 92: loss = 0.07269
epoch 92: loss = 0.05441
epoch 92: loss = 0.03635
epoch 92: loss = 0.38499
epoch 92: loss = 0.06567
epoch 92: loss = 0.05862
epoch 92: loss = 0.09496
epoch 92: loss = 0.03732
epoch 92: loss = 0.04018
epoch 92: loss = 0.09534
epoch 92: loss = 0.04255
epoch 92: loss = 0.05866
epoch 92: loss = 0.05209
epoch 92: loss = 0.07819
epoch 92: loss = 0.07995


epoch 106: loss = 0.06571
epoch 106: loss = 0.02490
epoch 106: loss = 0.03480
epoch 106: loss = 0.08276
epoch 106: loss = 0.05313
epoch 106: loss = 0.07013
epoch 106: loss = 0.03778
epoch 106: loss = 0.03451
epoch 106: loss = 0.36720
epoch 106: loss = 0.07339
epoch 106: loss = 0.02572
epoch 107: loss = 0.02440
epoch 107: loss = 0.04744
epoch 107: loss = 0.09899
epoch 107: loss = 0.02227
epoch 107: loss = 0.03172
epoch 107: loss = 0.04210
epoch 107: loss = 0.02470
epoch 107: loss = 0.02201
epoch 107: loss = 0.06699
epoch 107: loss = 0.08974
epoch 107: loss = 0.13733
epoch 107: loss = 0.09150
epoch 107: loss = 0.09190
epoch 107: loss = 0.09809
epoch 107: loss = 0.09029
epoch 107: loss = 0.06836
epoch 107: loss = 0.28617
epoch 107: loss = 0.04739
epoch 107: loss = 0.04108
epoch 107: loss = 0.07739
epoch 107: loss = 0.04679
epoch 107: loss = 0.06540
epoch 107: loss = 0.08217
epoch 107: loss = 0.04210
epoch 107: loss = 0.04333
epoch 108: loss = 0.05634
epoch 108: loss = 0.09742
epoch 108: l

epoch 120: loss = 0.11019
epoch 120: loss = 0.04290
epoch 120: loss = 0.04513
epoch 120: loss = 0.10681
epoch 120: loss = 0.04156
epoch 120: loss = 0.03589
epoch 120: loss = 0.02496
epoch 120: loss = 0.03546
epoch 120: loss = 0.03211
epoch 120: loss = 0.09846
epoch 120: loss = 0.05448
epoch 120: loss = 0.06520
epoch 120: loss = 0.05410
epoch 120: loss = 0.03532
epoch 121: loss = 0.08707
epoch 121: loss = 0.05392
epoch 121: loss = 0.04801
epoch 121: loss = 0.02293
epoch 121: loss = 0.05462
epoch 121: loss = 0.03417
epoch 121: loss = 0.06639
epoch 121: loss = 0.04925
epoch 121: loss = 0.02382
epoch 121: loss = 0.05139
epoch 121: loss = 0.01954
epoch 121: loss = 0.05318
epoch 121: loss = 0.26790
epoch 121: loss = 0.04543
epoch 121: loss = 0.08403
epoch 121: loss = 0.04595
epoch 121: loss = 0.03681
epoch 121: loss = 0.02853
epoch 121: loss = 0.06617
epoch 121: loss = 0.06117
epoch 121: loss = 0.10052
epoch 121: loss = 0.07229
epoch 121: loss = 0.03664
epoch 121: loss = 0.07475
epoch 121: l

epoch 134: loss = 0.02888
epoch 134: loss = 0.07244
epoch 134: loss = 0.03855
epoch 134: loss = 0.01877
epoch 135: loss = 0.03207
epoch 135: loss = 0.03962
epoch 135: loss = 0.05630
epoch 135: loss = 0.03463
epoch 135: loss = 0.05887
epoch 135: loss = 0.03910
epoch 135: loss = 0.06402
epoch 135: loss = 0.03150
epoch 135: loss = 0.04048
epoch 135: loss = 0.08178
epoch 135: loss = 0.05493
epoch 135: loss = 0.07779
epoch 135: loss = 0.06003
epoch 135: loss = 0.25891
epoch 135: loss = 0.02595
epoch 135: loss = 0.04414
epoch 135: loss = 0.01715
epoch 135: loss = 0.04759
epoch 135: loss = 0.03336
epoch 135: loss = 0.04791
epoch 135: loss = 0.07692
epoch 135: loss = 0.02703
epoch 135: loss = 0.06259
epoch 135: loss = 0.02778
epoch 135: loss = 0.01049
epoch 136: loss = 0.02048
epoch 136: loss = 0.03714
epoch 136: loss = 0.11189
epoch 136: loss = 0.05905
epoch 136: loss = 0.08600
epoch 136: loss = 0.04558
epoch 136: loss = 0.04071
epoch 136: loss = 0.04615
epoch 136: loss = 0.05415
epoch 136: l

epoch 149: loss = 0.20396
epoch 149: loss = 0.02126
epoch 149: loss = 0.03309
epoch 149: loss = 0.06826
epoch 149: loss = 0.04036
epoch 149: loss = 0.04514
epoch 149: loss = 0.02751
epoch 149: loss = 0.06028
epoch 149: loss = 0.02613
epoch 149: loss = 0.09650
epoch 149: loss = 0.03481
epoch 149: loss = 0.03639
epoch 149: loss = 0.03035
epoch 149: loss = 0.02596
epoch 149: loss = 0.02035
epoch 149: loss = 0.04943
epoch 149: loss = 0.03604
epoch 149: loss = 0.03710
epoch 149: loss = 0.02805
epoch 149: loss = 0.08316
epoch 150: loss = 0.04819
epoch 150: loss = 0.03600
epoch 150: loss = 0.03983
epoch 150: loss = 0.03914
epoch 150: loss = 0.03204
epoch 150: loss = 0.11381
epoch 150: loss = 0.05349
epoch 150: loss = 0.03322
epoch 150: loss = 0.02690
epoch 150: loss = 0.02297
epoch 150: loss = 0.03898
epoch 150: loss = 0.04393
epoch 150: loss = 0.02539
epoch 150: loss = 0.01853
epoch 150: loss = 0.03746
epoch 150: loss = 0.04133
epoch 150: loss = 0.07547
epoch 150: loss = 0.03851
epoch 150: l

epoch 162: loss = 0.02309
epoch 162: loss = 0.20022
epoch 162: loss = 0.01990
epoch 162: loss = 0.03496
epoch 162: loss = 0.03922
epoch 162: loss = 0.02814
epoch 162: loss = 0.03662
epoch 163: loss = 0.03449
epoch 163: loss = 0.02431
epoch 163: loss = 0.06408
epoch 163: loss = 0.02855
epoch 163: loss = 0.04498
epoch 163: loss = 0.20941
epoch 163: loss = 0.02176
epoch 163: loss = 0.04613
epoch 163: loss = 0.03289
epoch 163: loss = 0.03211
epoch 163: loss = 0.03107
epoch 163: loss = 0.07065
epoch 163: loss = 0.07785
epoch 163: loss = 0.02619
epoch 163: loss = 0.03557
epoch 163: loss = 0.03452
epoch 163: loss = 0.01963
epoch 163: loss = 0.04817
epoch 163: loss = 0.02686
epoch 163: loss = 0.02055
epoch 163: loss = 0.05023
epoch 163: loss = 0.05936
epoch 163: loss = 0.04393
epoch 163: loss = 0.04596
epoch 163: loss = 0.07386
epoch 164: loss = 0.03735
epoch 164: loss = 0.02312
epoch 164: loss = 0.01885
epoch 164: loss = 0.03988
epoch 164: loss = 0.01944
epoch 164: loss = 0.02970
epoch 164: l

epoch 177: loss = 0.10442
epoch 177: loss = 0.03175
epoch 177: loss = 0.03198
epoch 177: loss = 0.05429
epoch 177: loss = 0.05755
epoch 177: loss = 0.02655
epoch 177: loss = 0.04901
epoch 177: loss = 0.02779
epoch 177: loss = 0.01671
epoch 177: loss = 0.04355
epoch 177: loss = 0.05748
epoch 177: loss = 0.03759
epoch 177: loss = 0.01602
epoch 177: loss = 0.05553
epoch 177: loss = 0.02201
epoch 177: loss = 0.02153
epoch 177: loss = 0.04545
epoch 178: loss = 0.03995
epoch 178: loss = 0.04374
epoch 178: loss = 0.03561
epoch 178: loss = 0.21799
epoch 178: loss = 0.01806
epoch 178: loss = 0.03875
epoch 178: loss = 0.02707
epoch 178: loss = 0.05951
epoch 178: loss = 0.03492
epoch 178: loss = 0.02272
epoch 178: loss = 0.04730
epoch 178: loss = 0.02316
epoch 178: loss = 0.05517
epoch 178: loss = 0.03441
epoch 178: loss = 0.09364
epoch 178: loss = 0.03657
epoch 178: loss = 0.04711
epoch 178: loss = 0.04600
epoch 178: loss = 0.03903
epoch 178: loss = 0.03329
epoch 178: loss = 0.02530
epoch 178: l

epoch 191: loss = 0.05534
epoch 191: loss = 0.01981
epoch 191: loss = 0.05198
epoch 191: loss = 0.02291
epoch 191: loss = 0.04123
epoch 191: loss = 0.03599
epoch 191: loss = 0.02296
epoch 191: loss = 0.01865
epoch 191: loss = 0.02633
epoch 191: loss = 0.04023
epoch 191: loss = 0.06197
epoch 192: loss = 0.07023
epoch 192: loss = 0.01828
epoch 192: loss = 0.03699
epoch 192: loss = 0.06378
epoch 192: loss = 0.05291
epoch 192: loss = 0.05206
epoch 192: loss = 0.04696
epoch 192: loss = 0.03312
epoch 192: loss = 0.07304
epoch 192: loss = 0.02620
epoch 192: loss = 0.02649
epoch 192: loss = 0.02289
epoch 192: loss = 0.04830
epoch 192: loss = 0.03563
epoch 192: loss = 0.01527
epoch 192: loss = 0.05201
epoch 192: loss = 0.03334
epoch 192: loss = 0.02368
epoch 192: loss = 0.01354
epoch 192: loss = 0.02854
epoch 192: loss = 0.03437
epoch 192: loss = 0.04536
epoch 192: loss = 0.03941
epoch 192: loss = 0.21282
epoch 192: loss = 0.01991
epoch 193: loss = 0.04442
epoch 193: loss = 0.04128
epoch 193: l

epoch 208: loss = 0.04962
epoch 208: loss = 0.03910
epoch 208: loss = 0.04101
epoch 208: loss = 0.04372
epoch 208: loss = 0.02693
epoch 208: loss = 0.02270
epoch 208: loss = 0.01893
epoch 208: loss = 0.02615
epoch 208: loss = 0.01884
epoch 208: loss = 0.01620
epoch 208: loss = 0.02455
epoch 208: loss = 0.23416
epoch 208: loss = 0.03001
epoch 208: loss = 0.02458
epoch 208: loss = 0.03498
epoch 208: loss = 0.02630
epoch 208: loss = 0.06999
epoch 208: loss = 0.03399
epoch 208: loss = 0.02849
epoch 208: loss = 0.04549
epoch 208: loss = 0.06337
epoch 208: loss = 0.07253
epoch 208: loss = 0.01998
epoch 208: loss = 0.05169
epoch 208: loss = 0.02711
epoch 209: loss = 0.05051
epoch 209: loss = 0.02768
epoch 209: loss = 0.04696
epoch 209: loss = 0.04193
epoch 209: loss = 0.03285
epoch 209: loss = 0.04283
epoch 209: loss = 0.03020
epoch 209: loss = 0.07872
epoch 209: loss = 0.02952
epoch 209: loss = 0.05318
epoch 209: loss = 0.02707
epoch 209: loss = 0.05879
epoch 209: loss = 0.02384
epoch 209: l

epoch 224: loss = 0.02801
epoch 224: loss = 0.03785
epoch 224: loss = 0.02306
epoch 224: loss = 0.03514
epoch 224: loss = 0.08576
epoch 224: loss = 0.02205
epoch 225: loss = 0.02408
epoch 225: loss = 0.03345
epoch 225: loss = 0.09325
epoch 225: loss = 0.01992
epoch 225: loss = 0.03487
epoch 225: loss = 0.08227
epoch 225: loss = 0.01813
epoch 225: loss = 0.03518
epoch 225: loss = 0.03162
epoch 225: loss = 0.18649
epoch 225: loss = 0.05691
epoch 225: loss = 0.02695
epoch 225: loss = 0.02599
epoch 225: loss = 0.03557
epoch 225: loss = 0.03253
epoch 225: loss = 0.02581
epoch 225: loss = 0.03061
epoch 225: loss = 0.02452
epoch 225: loss = 0.04808
epoch 225: loss = 0.04662
epoch 225: loss = 0.02148
epoch 225: loss = 0.02605
epoch 225: loss = 0.02774
epoch 225: loss = 0.04320
epoch 225: loss = 0.04233
epoch 226: loss = 0.04111
epoch 226: loss = 0.02055
epoch 226: loss = 0.18825
epoch 226: loss = 0.02799
epoch 226: loss = 0.02147
epoch 226: loss = 0.04771
epoch 226: loss = 0.02792
epoch 226: l

epoch 238: loss = 0.01932
epoch 238: loss = 0.02384
epoch 238: loss = 0.02700
epoch 238: loss = 0.10206
epoch 238: loss = 0.02616
epoch 238: loss = 0.01712
epoch 238: loss = 0.07831
epoch 238: loss = 0.03265
epoch 238: loss = 0.04354
epoch 238: loss = 0.03227
epoch 238: loss = 0.04207
epoch 238: loss = 0.01691
epoch 238: loss = 0.02649
epoch 238: loss = 0.03574
epoch 238: loss = 0.04973
epoch 238: loss = 0.04047
epoch 238: loss = 0.25161
epoch 239: loss = 0.05042
epoch 239: loss = 0.03378
epoch 239: loss = 0.01861
epoch 239: loss = 0.02866
epoch 239: loss = 0.10423
epoch 239: loss = 0.05213
epoch 239: loss = 0.20021
epoch 239: loss = 0.04805
epoch 239: loss = 0.03527
epoch 239: loss = 0.06081
epoch 239: loss = 0.02824
epoch 239: loss = 0.08045
epoch 239: loss = 0.03057
epoch 239: loss = 0.02319
epoch 239: loss = 0.02331
epoch 239: loss = 0.02360
epoch 239: loss = 0.01847
epoch 239: loss = 0.03153
epoch 239: loss = 0.02080
epoch 239: loss = 0.01809
epoch 239: loss = 0.01697
epoch 239: l

epoch 251: loss = 0.22016
epoch 251: loss = 0.01759
epoch 251: loss = 0.03319
epoch 251: loss = 0.03221
epoch 251: loss = 0.03334
epoch 251: loss = 0.03528
epoch 251: loss = 0.02264
epoch 251: loss = 0.02988
epoch 251: loss = 0.02057
epoch 251: loss = 0.02228
epoch 251: loss = 0.04332
epoch 251: loss = 0.04295
epoch 251: loss = 0.02945
epoch 251: loss = 0.06140
epoch 251: loss = 0.02984
epoch 251: loss = 0.02299
epoch 251: loss = 0.04062
epoch 251: loss = 0.03448
epoch 251: loss = 0.10051
epoch 252: loss = 0.03469
epoch 252: loss = 0.02365
epoch 252: loss = 0.02015
epoch 252: loss = 0.23072
epoch 252: loss = 0.02544
epoch 252: loss = 0.02370
epoch 252: loss = 0.03606
epoch 252: loss = 0.02708
epoch 252: loss = 0.02141
epoch 252: loss = 0.04533
epoch 252: loss = 0.04836
epoch 252: loss = 0.07316
epoch 252: loss = 0.04060
epoch 252: loss = 0.03934
epoch 252: loss = 0.02873
epoch 252: loss = 0.03758
epoch 252: loss = 0.01515
epoch 252: loss = 0.03698
epoch 252: loss = 0.03215
epoch 252: l

epoch 264: loss = 0.01921
epoch 264: loss = 0.01553
epoch 264: loss = 0.03522
epoch 264: loss = 0.18564
epoch 264: loss = 0.01835
epoch 264: loss = 0.03040
epoch 264: loss = 0.05660
epoch 264: loss = 0.02870
epoch 264: loss = 0.02688
epoch 264: loss = 0.09004
epoch 264: loss = 0.03658
epoch 264: loss = 0.05433
epoch 264: loss = 0.03650
epoch 264: loss = 0.02679
epoch 265: loss = 0.03966
epoch 265: loss = 0.04189
epoch 265: loss = 0.02453
epoch 265: loss = 0.02227
epoch 265: loss = 0.02642
epoch 265: loss = 0.07685
epoch 265: loss = 0.02274
epoch 265: loss = 0.18167
epoch 265: loss = 0.05151
epoch 265: loss = 0.04509
epoch 265: loss = 0.03573
epoch 265: loss = 0.03117
epoch 265: loss = 0.03976
epoch 265: loss = 0.08907
epoch 265: loss = 0.03842
epoch 265: loss = 0.02929
epoch 265: loss = 0.02370
epoch 265: loss = 0.02158
epoch 265: loss = 0.01520
epoch 265: loss = 0.02910
epoch 265: loss = 0.02531
epoch 265: loss = 0.04551
epoch 265: loss = 0.02255
epoch 265: loss = 0.05837
epoch 265: l

epoch 278: loss = 0.02627
epoch 278: loss = 0.03872
epoch 278: loss = 0.18189
epoch 278: loss = 0.02703
epoch 278: loss = 0.04697
epoch 278: loss = 0.03514
epoch 278: loss = 0.04465
epoch 278: loss = 0.02235
epoch 278: loss = 0.03746
epoch 278: loss = 0.02750
epoch 278: loss = 0.03168
epoch 278: loss = 0.01807
epoch 278: loss = 0.04729
epoch 278: loss = 0.01287
epoch 278: loss = 0.01580
epoch 278: loss = 0.04777
epoch 278: loss = 0.11324
epoch 278: loss = 0.05046
epoch 278: loss = 0.06611
epoch 279: loss = 0.02056
epoch 279: loss = 0.07670
epoch 279: loss = 0.01922
epoch 279: loss = 0.05233
epoch 279: loss = 0.03825
epoch 279: loss = 0.03407
epoch 279: loss = 0.02042
epoch 279: loss = 0.03242
epoch 279: loss = 0.02601
epoch 279: loss = 0.05161
epoch 279: loss = 0.02356
epoch 279: loss = 0.04211
epoch 279: loss = 0.04211
epoch 279: loss = 0.02326
epoch 279: loss = 0.02822
epoch 279: loss = 0.02654
epoch 279: loss = 0.03077
epoch 279: loss = 0.01955
epoch 279: loss = 0.06027
epoch 279: l

epoch 294: loss = 0.01388
epoch 294: loss = 0.01354
epoch 294: loss = 0.04712
epoch 294: loss = 0.02460
epoch 294: loss = 0.02061
epoch 294: loss = 0.01263
epoch 294: loss = 0.01651
epoch 294: loss = 0.02272
epoch 294: loss = 0.04890
epoch 294: loss = 0.05481
epoch 294: loss = 0.02037
epoch 294: loss = 0.01750
epoch 294: loss = 0.19674
epoch 294: loss = 0.03635
epoch 294: loss = 0.01785
epoch 294: loss = 0.05930
epoch 294: loss = 0.05708
epoch 294: loss = 0.03011
epoch 294: loss = 0.05465
epoch 294: loss = 0.03984
epoch 295: loss = 0.02755
epoch 295: loss = 0.02159
epoch 295: loss = 0.08243
epoch 295: loss = 0.04166
epoch 295: loss = 0.03247
epoch 295: loss = 0.02320
epoch 295: loss = 0.02871
epoch 295: loss = 0.02497
epoch 295: loss = 0.04631
epoch 295: loss = 0.03736
epoch 295: loss = 0.03282
epoch 295: loss = 0.06664
epoch 295: loss = 0.05488
epoch 295: loss = 0.01744
epoch 295: loss = 0.01483
epoch 295: loss = 0.05882
epoch 295: loss = 0.04940
epoch 295: loss = 0.16697
epoch 295: l

In [5]:
view = np.concatenate((np.rint(pred_values), y_test), axis = 1)
print(view)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 2.  3.]
 [ 0.  0.]
 [ 1.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [-0.  0.]
 [-0.  0.]
 [ 0.  0.]
 [ 1.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 1.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 1.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 3.  4.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 1.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 1.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 1.  1.]
 [ 1.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 1.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]